### ISSUE TITLE
processInput crash

### ISSUE THREAD

**Issue by DetonDev** [Maugrift/EverSector#1]
Game crashed. I got this crash.txt:

`The game has crashed! Please send the contents of this file to the developer to help fix the problem.
boldorf.eversector.screens.SectorScreen.processInput(SectorScreen.java:167)
boldorf.eversector.screens.GameScreen.processInput(GameScreen.java:178)
boldorf.apwt.Display.keyPressed(Display.java:83)
java.desktop/java.awt.Component.processKeyEvent(Component.java:6590)
java.desktop/java.awt.Component.processEvent(Component.java:6409)
java.desktop/java.awt.Container.processEvent(Container.java:2263)
java.desktop/java.awt.Window.processEvent(Window.java:2049)
java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:870)
java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1139)
java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)
java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4889)
java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
java.base/java.security.AccessController.doPrivileged(Native Method)
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
java.base/java.security.AccessController.doPrivileged(Native Method)
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by Maugrift** [comment]
Thanks for posting. Could you share any more information about what you were doing when the crash occurred? Also, what version of the game was this? I'll be honest, it's not super likely that I'll get around to fixing this issue, but it would be useful information if anyone wants to tackle it in the future.

(Also, I now realize that I probably should've included more information in these crash logs...)

**Comment by DetonDev** [comment]
I was using the most recent Linux version of the game, downloaded from itch.io

I experience this crash every time I push the right arrow during gameplay. Quite odd!

**Comment by Maugrift** [comment]
Huh, that was fixed in v0.7.1 but it looks like it didn't get uploaded to itch properly. I just reuploaded the v0.7.1 releases from GitHub to itch; try downloading again and see if it works.

**Comment by DetonDev** [comment]
Downloaded the new version and everything seems to be working properly. Thanks!

**Comment by Maugrift** [comment]
Great! I'm not sure how I didn't notice the problem with the itch version sooner, but I'm glad you posted this so I could get it fixed.
